# Generated by Django 4.1.7 on 2023-02-21 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_remove_comment_name_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
